version: '2'
services:
 
 mysql:
    build: ./mysql-docker/5.6 
    container_name: eLodDrupalmySQL
    #image: mysql:5.6
    volumes:
     - /mysql_drupal:/var/lib/mysql 
    environment:
     - MYSQL_DATABASE=drupalelod
     - MYSQL_ROOT_PASSWORD=eLodmysqlpass
    restart: on-failure

 virtuoso:
   build: ./docker-virtuoso
   container_name: eLodVirtuoso
   ports:
   - 8890:8890
   volumes:
   - /virtuoso/db:/var/lib/virtuoso/db 
   environment:
   - DBA_PASSWORD=eLodVir 
   - SPARQL_UPDATE=true 
   - DEFAULT_GRAPH=http://localhost:8890/DAV 
 
 drupal: 
    build: ./docker-drupal
    command:
    - /start.sh 
    depends_on:
    - mysql
    container_name: eLodDrupal
    #image: eLodDrupal 
    ports: 
    - "8081:80"
    volumes:
    - "/data_drupal:/var/www/html" 
    links:
    - "mysql"
    environment:
     - MYSQL_DATABASE=drupalelod
     - MYSQL_USER=root
     - MYSQL_PASSWORD=eLodmysqlpass
     - DRUPAL_ADMIN_PW=eLODDR
     - DRUPAL_ADMIN=admin
     - MYSQL_HOST=eLodDrupalmySQL
     - DRUPAL_ADMIN_EMAIL=stetsiafoulis@gmail.com
    restart: on-failure
 db:
   image: kartoza/postgis:9.4-2.1
   environment:
    - USERNAME=docker
    - PASS=docker

 qgisdesktop:
   #image: kartoza/qgis-desktop:2.14
   build: ./qgis-desktop/2.14  
   hostname: qgis-server
   volumes:
    #Wherever you want to mount your data from
   - ./gis:/gis
    #Unix socket for X11
   - "/tmp/.X11-unix:/tmp/.X11-unix"
   links:
   - db:db
   environment: 
   - DISPLAY=unix:1
   command: /usr/bin/qgis
